---
title: "01: tidypollute: Getting to Know the Package"
author: "Dr. Nelson Roque"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{01: tidypollute: Getting to Know the Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Goals of this Notebook

This notebook orients you to `tidypollute` functions in a functional example (pun intended).

------------------------------------------------------------------------

This request receives data from EPA AirData flat files, for **analyte** (pollutant) == `LEAD` over a given time range.

```{r, message=F, warning=F}
library(tidypollute)
```

## Get Analyte Codes
```{r}
tidypollute::epa_analyte_codes
```

## Get Zip Links for all Files
```{r}
epa_zip_links <- get_epa_airdata_zip_links()
head(epa_zip_links)
```

## Get Data: Lead, from 1999-2000
```{r, message=F, warning=F, echo=T}
lead <- get_epa_airdata(analyte = "LEAD", 
                        start_year = 1999, 
                        end_year = 2000, 
                        freq = "daily")
```

------------------------------------------------------------------------

## Summary

This notebook provides an orientation to the various `tidypollute` functions.

For more details, check out [`tidypollute` documentation](https://nelsonroque.github.io/tidypollute/index.html).
