---
title: "tidypollute: Linking to Health Outcomes/Patient Data"
author: "Dr. Nelson Roque"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tidypollute: Linking to Health Outcomes/Patient Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# tidypollute: Getting to Know the Package

## Goals of this Notebook

This notebook orients you to `tidypollute` functions in a functional example (pun intended).

------------------------------------------------------------------------

This request receives data from EPA AirData flat files, for **analyte** (pollutant) == `LEAD` over a given time range (1999-2000), and links it to fake participant data.

```{r, message=F, warning=F, echo=F}
library(tidypollute)
lead <- get_epa_airdata(analyte = "LEAD", 
                        start_year = 1999, 
                        end_year = 2000, 
                        freq = "daily")
```

## Load participant data

This is sample participant data, where you have a de-identified `participant_id`, other variables (`age`, `smoking_status`, and `dementia` status), and a set of dates for which to compute exposures within (`start_date`, `end_date`). If you need to compute many windows for a given participant, the idea would be to have as many rows in participants_df as you need data lookups for computing exposures.

```{r}

participants_df <- tibble::tibble(
  participant_id = 1:5,
  start_date = as.Date(c("1999-06-01", "1999-01-01", "1999-03-15", "1999-07-10", "1999-09-20")),
  end_date = as.Date(c("2000-12-31", "2000-12-31", "2000-09-30", "2000-05-20", "2000-06-15")),
  age = c(65, 72, 50, 60, 58),
  smoking_status = c("Never", "Former", "Current", "Never", "Former"),
  dementia = c(0,1,1,0,1)
)

```

```{r, echo=F, message=F, warning=F}
exposure_df = summarise_exposure(participants_df=participants_df,
                               air_quality_df=lead,
                               date_col="date_local",
                               pollutant_col="arithmetic_mean",
                               start_col="start_date",
                               end_col="end_date",
                               group_vars = c("participant_id", "age", "smoking_status", "dementia"))

```

```{r}
exposure_df
```

------------------------------------------------------------------------

## Summary

This notebook provides an orientation how you can leverage `tidypollute` data and merge with participant/health outcome data.

For more details, check out [`tidypollute` documentation](https://nelsonroque.github.io/tidypollute/index.html).
